### ISSUE TITLE
워크스페이스 추가

### ISSUE THREAD

**Issue by dungsil** [web-developer-survey/web-developer-survey#14]
현재 프로젝트가 모노레포 형식이 되어 있어 워크스페이스를 추가하여 루트에서 전역으로 관리할 수 있게 하면 어떨까요?

## 도입 시 장점
1. `node_modules`, `package-lock.json`을 루트 디렉토리에서 하나로 관리 가능
2. 루트 디렉토리에서 스크립트 실행 가능
   예시) `npm run dev -w=backend`
3. 동시 빌드 등 가능
   예시) `npm run build -w frontend -w backend`

## 단점
1. Node.js v12.13 이상 혹은 v14 이상 사용필요
2. NPM v8 이상 사용 필요

## 추가 방법

**package.json**
```json5
{
  // ...
  "workspaces": {
    "packages": [
      "backend/",
      "frontend/"
    ]
  },
  // ...
}
```

**Comment by 2Ruk** [comment]
좋은 제안 감사합니다! 
말씀 주신 부분에 대하여 알아본 후 적용할 수 있도록 하겠습니다..!
모르는 부분은 조금 여쭈어볼게요 ✨😀
좋은 제안 다시 한번 감사합니다.❕❗❕
