### ISSUE TITLE
🙋 도움을 요청합니다! [ mono-repo ]😢 

### ISSUE THREAD

**Issue by 2Ruk** [web-developer-survey/web-developer-survey#15]
### 🍏 **원하는 해결 사항:**

1️⃣ web-developer-survey/node_modules 단일 관리 

2️⃣ web-developer-survey/package.json 의 scripts로 전역 빌드 및 실행

→해결하기 위해 아래 과정의 학습 및 설정이 필요한가요❓

1. yarn 
2. lerna

해결을 위해 참고해본 사이트 😥

1. [https://docs.npmjs.com/cli/v8/using-npm/workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces)
2. [https://yceffort.kr/2021/07/npm-workspaces-esbuild](https://yceffort.kr/2021/07/npm-workspaces-esbuild)
3. [https://intrepidgeeks.com/tutorial/simplify-monupo-with-npm7-workspace](https://intrepidgeeks.com/tutorial/simplify-monupo-with-npm7-workspace)
4. [https://github.com/modernweb-pl/vue-nest-monorepo/blob/master/package.json](https://github.com/modernweb-pl/vue-nest-monorepo/blob/master/package.json)

---

### 🚨  문제사항

1️⃣ web-developer-survey 경로에서 npm i 를 진행하면  아래 세가지 경로에 **각각 node_module이 설치** 됩니다!

1. web-developer-survey/ ⚠️node_modules
2. web-developer-survey/backend/ ⚠️node_modules
3. web-developer-survey/frontend/ ⚠️node_modules

2️⃣ web-developer-sruvey/package.json scsripts 실행 시 

1. 문제사항1️⃣ 처럼 node modules이 설치되어 있는 경우 실행 됩니다.
2. backend , frontend 의 node_modules을 제거할 시 🍒module not found의 오류가 발생

설정되어 있는 항목은 아래와 같습니다.

```tsx

...,
"scripts": {
    "back": "npm run start:dev -w=backend",
    "front": "npm run serve -w=frontend",
    "build": "npm run build -w frontend -w backend"
},
"workspaces": {
    "packages": [
      "backend/",
      "frontend/"
    ],
    "nohoist": [ 
      "**/@vue/cli-service"
    ]
    // nohoist옵션은 git참고: https://github.com/modernweb-pl/vue-nest-monorepo 
}
```

---

### 파일경로

<aside>
🌐 파일 경로

**web-developer-survey**

ㄴ1️⃣backend

- package.json
- package-lock.json

ㄴ2️⃣frontend

- package.json
- package-lock.json

3️⃣.gitignore

4️⃣.prettiterrc

5️⃣pacakge.json

6️⃣pacakge-lock.json

</aside>

---

관련 이슈: #14

**Comment by dungsil** [comment]
> →해결하기 위해 아래 과정의 학습 및 설정이 필요한가요❓
> 
>     1. yarn
> 
>     2. lerna

현재 저장소가 복잡한 형식이 아니라 아직 따른 도구를 도입하진 않아도 될 거 같습니다.

**Comment by dungsil** [comment]
> 1️⃣ web-developer-survey 경로에서 npm i 를 진행하면 아래 세가지 경로에 **각각 node_module이 설치** 됩니다!
> 
>     1. web-developer-survey/ ⚠️node_modules
> 
>     2. web-developer-survey/backend/ ⚠️node_modules
> 
>     3. web-developer-survey/frontend/ ⚠️node_modules
> 
> 
> 2️⃣ web-developer-sruvey/package.json scsripts 실행 시
> 
>     1. 문제사항1️⃣ 처럼 node modules이 설치되어 있는 경우 실행 됩니다.
> 
>     2. backend , frontend 의 node_modules을 제거할 시 🍒module not found의 오류가 발생

각 패키지 별로 동일한 패키지의 다른 버전을 설치하려고 할 때 충돌을 방지하기 위해서 서브 디렉토리에 `node_modules`가 생성되어 따로 관리됩니다.  버전을 동일하게 맞추는 작업을 하거나 현재 상태가 올바른 상태로 보입니다.

**Comment by dungsil** [comment]
**현재 충돌되는 모듈**

1. `@types/node`
2. `@vue/cli-service`
3. `eslint`
4. `typescript`

**Comment by dungsil** [comment]
> ㄴ1️⃣backend
> 
>     * package.json
> 
>     * package-lock.json
> 
> 
> ㄴ2️⃣frontend
> 
>     * package.json
> 
>     * package-lock.json

서브 디렉토리의 `package-lock.json`파일은 이제 사용되지 않으니 제거해주시면 됩니다.

**Comment by 2Ruk** [comment]
매우 매우 자세한 피드백 감사합니다! 
몰랐던 부분에 대해 많이 알고 가게 되었습니다.
정말 최고! 💨 말로 표현할 수 없네요.

정말 감사드립니다!
