### ISSUE TITLE
[RESULT] 결과페이지 차트 Interface

### ISSUE THREAD

**Issue by 2Ruk** [web-developer-survey/web-developer-survey#36]
## ChartData 인터페이스 관련

```tsx
export namespace Chart {
  export interface Series {
    name: string;
    data: number[];
  }

  export interface Dataset {
    categories: string[];
    series: Series[];
  }
}
```

### 인터페이스 설명

---

1️⃣**목적**: 결과 페이지 차트에 공통적으로 사용할 인터페이스

2️⃣**설명 -** [https://nhn.github.io/tui.chart/latest/tutorial-example02-01-bar-chart-basic](https://nhn.github.io/tui.chart/latest/tutorial-example02-01-bar-chart-basic)

toast ui chart의 기본적으로 제공되는 option을 따라가기로 했습니다!
![image](https://user-images.githubusercontent.com/94098919/174111500-0899c15a-efeb-4f27-b8d1-79331189941a.png)

**Comment by 2Ruk** [comment]
그리고 이건 작성했던게 아쉬워서..올리는..댓글... ㅠㅠ.. ( option 값 보기이전에 제가 작성하였던 interface ) 

## ChartData 인터페이스 관련

```tsx
export namespace Chart {
  export interface Content {
    chapter: number;
    title: string;
    description: string;
  }

  export interface Label {
    idx: number;
    label: string;
    totalCnt: number;
  }

  export interface Data {
    idx: number;
    percent: number;
    cnt: number;
  }

  export interface Text {
    text: string;
    cnt: number;
    idx: number;
  }
  
  export interface Category{
    idx: number;
    category: string;
  }
  
  export interface Dataset extends Content {
    data: Data[][];
    labels: Label[];
    category: Category[];
    texts?: Text[];
  }
}

const exampleChartData: Chart.Dataset = {
  chapter: 1,
  title: 'Chapter1. 참여자 구성',
  description: '이웃 세워 보고, 듯 합니다. 풀이위에도 등 설명입니다.',
  category: [
    { idx: 0, category: '프론트엔드' },
    { idx: 1, category: '백엔드' },
    { idx: 2, category: '풀스택' },
  ],
  labels: [
    { idx: 0, label: '1년차', totalCnt: 5 },
    { idx: 1, label: '2년차', totalCnt: 5 },
    { idx: 2, label: '3년차', totalCnt: 5 },
  ],
  data: [
    [
      { idx: 0, cnt: 1, percent: 20 },
      { idx: 1, cnt: 2, percent: 40 },
      { idx: 2, cnt: 2, percent: 40 },
    ],
    [
      { idx: 0, cnt: 2, percent: 40 },
      { idx: 1, cnt: 2, percent: 40 },
      { idx: 2, cnt: 1, percent: 20 },
    ],
    [
      { idx: 0, cnt: 2, percent: 40 },
      { idx: 1, cnt: 1, percent: 20 },
      { idx: 2, cnt: 2, percent: 40 },
    ],
  ],

  texts: [
    { idx: 0, cnt: 2, text: '기타값  1' },
    { idx: 1, cnt: 1, text: '기타값  2' },
  ],
};
```

### 인터페이스 설명

---

1️⃣**목적**: 결과 페이지 차트에 공통적으로 사용할 인터페이스

2️⃣**설명 -** exampleChartData기준으로 설명

1. chapter : 사용될 챕터
2. title: 챕터 설명문의 타이틀 
3. description: 챕터 설명문의 본문
4. category:   유형별 묶음 (  multibar 기준으로 데이터값 한줄,한줄에 대한   ) 
5. labels:  보기에 대한 정보 
6. data: 아래 이미지 ! 참고가 이해에 도움이 될 것 같습니다!
7. texts: 혹시 기타값 입력이 필요할 때 쓰려고 만든 항목입니다!

![image](https://user-images.githubusercontent.com/94098919/174112179-446e6bd9-cb1d-473e-aa36-c07657097870.png)

**Comment by 2Ruk** [comment]
> ## ChartData 인터페이스 관련
> ```tsx
> export namespace Chart {
>   export interface Series {
>     name: string;
>     data: number[];
>   }
> 
>   export interface Dataset {
>     categories: string[];
>     series: Series[];
>   }
> }
> ```
> 
> ### 인터페이스 설명
> 1️⃣**목적**: 결과 페이지 차트에 공통적으로 사용할 인터페이스
> 
> 2️⃣**설명 -** https://nhn.github.io/tui.chart/latest/tutorial-example02-01-bar-chart-basic
> 
> toast ui chart의 기본적으로 제공되는 option을 따라가기로 했습니다! ![image](https://user-images.githubusercontent.com/94098919/174111500-0899c15a-efeb-4f27-b8d1-79331189941a.png)

이렇게 하면 좋을것 같아 의논드립니다! @dungsil 
좋은밤 되세요!

**Comment by dungsil** [comment]
차트데이터는 #35 와 함께 API에서 제공되나요? 아니면 다른 URL로 요청을 해야하나요?

**Comment by 2Ruk** [comment]
> 차트데이터는 #35 와 함께 제공되나요? 아니면 다른 URL로 요청을 해야하나요?

헉..뭔갈 잘못누른거같네요.. 일단 좋은 방안을 위해 고민해보고, 답변 드리겠습니다..!!

**Comment by 2Ruk** [comment]
> 차트데이터는 #35 와 함께 제공되나요? 아니면 다른 URL로 요청을 해야하나요?

export interface Text {
  chapter: number,
  title: string,
  summary: string,
  description: string,
}

export namespace Chart {
  export interface Series {
    name: string;
    data: number[];
  }

  export interface Data {
    idx: number; // 데이터 순서 ( chart 순서 )
    categories: string[]; // toast ui chart option
    series: Series[]; // toast ui chart option
  }
}

export interface Result extends Text {
    resultData: Chart.Data[]
}
혹시 이렇게 제공 되면 어떨까요? 감사합니다 둥실님 ㅠ_ㅠ

**Comment by dungsil** [comment]
LGTM 👍
