### ISSUE TITLE
[RESULT] tui.chart 유지보수가 안되는 문제

### ISSUE THREAD

**Issue by dungsil** [web-developer-survey/web-developer-survey#43]
현재 TOAST UI Chart가 유지보수가 안되는 걸로 보입니다. Chart.js나 기타 라이브러리로 변경할 필요가 있을 거 같습니다,
관련 이슈: tui.chart#749

**Comment by 2Ruk** [comment]
앗 해당 부분 검토 진행하겠습니다!

**Comment by dungsil** [comment]
네네 chart.js 가 젤 무난하게 쓰기 좋은 거 같아요 😊
